services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autowiring
  Ang3\Bundle\MoneyBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources}'

  Ang3\Bundle\MoneyBundle\Config\MoneyConfig:
    public: true
