services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autowiring
  Ang3\Bundle\MoneyBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Resources}'

  Ang3\Bundle\MoneyBundle\Config\MoneyConfig:
    arguments:
      $parameters: '%ang3_money.config%'
    public: true

  Ang3\Bundle\MoneyBundle\Money\CurrencyRegistry:
    factory: [null, create]
    arguments:
      $config: '%ang3_money.config%'
    public: true
