services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autowiring
  Ang3\Bundle\MoneyBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Resources}'

  Ang3\Bundle\MoneyBundle\Config\MoneyConfig:
    arguments:
      $parameters: '%ang3_money.config%'

  money_config:
    alias: Ang3\Bundle\MoneyBundle\Config\MoneyConfig
    public: true

  Ang3\Bundle\MoneyBundle\Money\CurrencyRegistry:
    factory: [null, create]
    arguments:
      $config: '@Ang3\Bundle\MoneyBundle\Config\MoneyConfig'

  currency_registry:
    alias: Ang3\Bundle\MoneyBundle\Money\CurrencyRegistry
    public: true

  Ang3\Bundle\MoneyBundle\Money\CurrencyRegistryProvider:
    calls:
      - [ 'setRegistry', ['@currency_registry'] ]

  currency_provider:
    alias: Ang3\Bundle\MoneyBundle\Money\CurrencyRegistryProvider
    public: true